version: '3'
services:
  stellar-core-postgres:
    image: postgres:12
    restart: on-failure
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      # POSTGRES_DB=stellar-core
      # POSTGRES_PASSWORD=rEeJdGvWXNqiYnToBJEo

  stellar-core:
    image: pinetwork/stellar-core:12.5.0
    restart: on-failure
    volumes:
      - core-data:/data
    environment:
      - DATABASE=postgresql://dbname=stellar-core user=postgres password=DATABASE_PASSWORD host=stellar-core-postgres
      - DATABASE_PASSWORD=rEeJdGvWXNqiYnToBJEo
      - INITIALIZE_DB=false
      - INITIALIZE_HISTORY_ARCHIVES=false
      # public key GACVY6FX6ZSGBEWQF6DG25VOAB25F72EI4WS676QIO3HO2YBKAKDI44H
      # NODE_SEED="SDEZOI3BOCW6DUY23ZCJQALULOIEIQMZW4UTFXPRQEMMJMOG7CVD7WMO"
      - NODE_IS_VALIDATOR=true
      - NETWORK_PASSPHRASE="Pi Testnet"
      - MAX_PEER_CONNECTIONS=30
      - "KNOWN_PEERS=\
        testnet1.minepi.com:31402,\
        testnet2.minepi.com:31402,\
        testnet3.minepi.com:31402"
      - "PREFERRED_PEERS=\
        testnet1.minepi.com:31402,\
        testnet2.minepi.com:31402,\
        testnet3.minepi.com:31402"
      - "NODE_NAMES=\
        GC6R2IQ7LAEWFFNV2ZMXPMOLGGCFRFX6NQFCNT2PLB3KVJPHTIYV4ZPR testnet1,\
        GDRIZZC5PNZ6XBJTBZX52WX4NQ2K4Y5XBKVBRYNFDDS4VO6POQ3IGZCL testnet2,\ 
        GAKI7FNXWIJHKV4CKFSU6KDNFTPYAUOP2WIKL5IFSOPEUSYK4Y3LWMXX testnet3"
      - >-
          QUORUM_SET=[
            {
              "threshold_percent": 66,
              "validators": [
                "$$testnet1",
                "$$testnet2",
                "$$testnet3"
              ]
            }
          ]
      - KNOWN_CURSORS=HORIZON
      - UNSAFE_QUORUM=true
      - FAILURE_SAFETY=1
      - >-
          HISTORY={
            "pinetwork-testnet": {"get": "curl -sf https://history.testnet.minepi.com/{0} -o {1}"},
          }

volumes:
  db-data:
  core-data:
